STCOR-599: Display different message when user attempts to access the set password link when still logged in
folio-org/stripes-core pull request #1181
Opened 2022-04-12 11:55 UTC by mariiaschv

## Purpose
Display different message when user attempts to access the set password link when still logged in.

Issue: [STCOR-599](https://issues.folio.org/browse/STCOR-599)

2022-04-12 15:15 UTC, zburke requested changes
I don't think this is the right fix. It changes the message for _all_ bad requests. e.g. somebody who accesses a URL like https://folio-snapshot.dev.folio.org/asdfasdfasdf, would see "Please log out..." instead of "The requested URL was not found." 

Maybe this work can be done directly in `./src/components/CreateResetPassword/`, or maybe `./src/RootWithIntl.js` where that component is invoked, in order to correctly limit its scope?

2022-04-12 16:44 UTC, mariiaschv commented
> I don't think this is the right fix. It changes the message for _all_ bad requests. e.g. somebody who accesses a URL like https://folio-snapshot.dev.folio.org/asdfasdfasdf, would see "Please log out..." instead of "The requested URL was not found."
> 
> Maybe this work can be done directly in `./src/components/CreateResetPassword/`, or maybe `./src/RootWithIntl.js` where that component is invoked, in order to correctly limit its scope?

@zburke thank you! I wasn't attentive when implemented this. Fixed it and also attached gif to the description of the PR.

2022-04-12 18:22 UTC, zburke approved these changes
That was quick! :shipit:

2022-04-15 11:45 UTC, BogdanDenis approved these changes

2022-04-15 11:50 UTC, merged